"""
Build Python sidecar untuk Tauri menggunakan cx_Freeze (alternatif Nuitka/PyInstaller).
FULL SUPPORT: YOLO + Ultralytics + GPU (CUDA)

Opsi saat ini:
  1. Nuitka    → binaries/           (npm run build:sidecar)
  2. PyInstaller → binaries_pyinstaller/
  3. cx_Freeze → binaries/  (npm run build:sidecar:cxfreeze)

cx_Freeze: folder output (exe + deps), startup sering lebih cepat dari PyInstaller.
"""
import os
import sys
import subprocess
from pathlib import Path


def get_target_triple():
    """Get Rust target triple untuk platform saat ini."""
    result = subprocess.run(
        ["rustc", "--print", "target-triple"],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        return result.stdout.strip()
    if sys.platform == "win32":
        return "x86_64-pc-windows-msvc"
    elif sys.platform == "darwin":
        return "aarch64-apple-darwin" if "arm" in os.uname().machine else "x86_64-apple-darwin"
    else:
        return "x86_64-unknown-linux-gnu"


def ensure_cxfreeze():
    """Ensure cx_Freeze installed."""
    try:
        import cx_Freeze  # noqa: F401
        print(f"cx_Freeze detected: {getattr(cx_Freeze, '__version__', '?')}")
        return True
    except ImportError:
        pass
    print("Installing cx_Freeze...")
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "cx_Freeze"],
        check=True,
    )
    print("cx_Freeze installed successfully.")
    return True


def build_sidecar_cxfreeze(script_name: str, output_name_base: str) -> bool:
    """Build Python sidecar menggunakan cx_Freeze."""
    import shutil

    script_dir = Path(__file__).parent
    src_tauri_dir = script_dir.parent
    python_ai_dir = src_tauri_dir / "python_ai"
    out_dir = src_tauri_dir / "binaries"

    out_dir.mkdir(exist_ok=True)

    worker_script = python_ai_dir / script_name
    if not worker_script.exists():
        print(f"ERROR: {worker_script} tidak ditemukan!")
        return False

    print(f"Building Python sidecar dengan cx_Freeze dari {worker_script}")

    target_triple = get_target_triple()
    output_name = f"{output_name_base}-{target_triple}"
    exe_suffix = ".exe" if sys.platform == "win32" else ""
    final_exe = output_name + exe_suffix

    print(f"Target triple: {target_triple}")
    print(f"Output name: {output_name}")
    print(f"Output dir:  {out_dir} (exe + deps)")

    setup_py = python_ai_dir / "setup_cxfreeze_infer.py"
    setup_content = f'''"""Temp setup for cx_Freeze build (generated by build_python_sidecar_cxfreeze.py)."""
# Kurangi RecursionError saat cx_Freeze scan torch/ultralytics (dependency chain dalam)
import sys
sys.setrecursionlimit(10000)

from cx_Freeze import Executable, setup

OUT_DIR = {repr(str(out_dir))}
OUTPUT_NAME = {repr(output_name)}
SCRIPT = {repr(str(worker_script))}
BASE = "gui" if sys.platform == "win32" else None

build_exe_options = {{
    "build_exe": OUT_DIR,
    "packages": ["torch", "torchvision", "ultralytics", "numpy", "PIL", "cv2",
                 "geojson", "shapely", "geopandas", "fastkml", "yaml", "tqdm", "sympy"],
    "includes": [
        "torch._C", "torch.backends.cuda", "torch.backends.cudnn",
        "torch.distributed", "torch.distributed.nn",
        "unittest",
    ],
    "excludes": [
        "tkinter", "test", "pytest", "IPython", "jupyter", "jupyter_client",
        "matplotlib", "scipy", "pandas.tests", "PIL.ImageQt", "setuptools",
    ],
    "zip_include_packages": ["encodings"],
    "zip_exclude_packages": ["*"],
}}
if sys.platform == "win32":
    build_exe_options["include_msvcr"] = True

setup(
    name="infer_worker",
    version="1.0",
    options={{"build_exe": build_exe_options}},
    executables=[Executable(script=SCRIPT, base=BASE, target_name=OUTPUT_NAME)],
)
'''
    try:
        setup_py.write_text(setup_content, encoding="utf-8")
        print("\nRunning cx_Freeze build_exe...")
        print("=" * 70)
        r = subprocess.run(
            [sys.executable, str(setup_py), "build_exe"],
            cwd=str(python_ai_dir),
            env={**os.environ, "PYTHONIOENCODING": "utf-8"},
            check=False,
        )
        print("=" * 70 + "\n")
        if r.returncode != 0:
            print(f"❌ cx_Freeze build_exe failed (exit {r.returncode})")
            return False
    finally:
        if setup_py.exists():
            setup_py.unlink(missing_ok=True)

    out_path = out_dir / final_exe
    if not out_path.exists():
        for cand in [out_dir / output_name, out_dir / (output_name + ".exe")]:
            if cand.exists():
                if cand != out_path:
                    shutil.move(str(cand), str(out_path))
                break
        else:
            print(f"ERROR: Output tidak ditemukan: {out_path}")
            if out_dir.exists():
                for f in sorted(out_dir.iterdir()):
                    print(f"  - {f.name}")
            return False

    size_mb = out_path.stat().st_size / (1024 * 1024)
    print(f"✓ Sidecar cx_Freeze OK: {out_path}")
    print(f"  Size exe: {size_mb:.1f} MB (folder berisi exe + dll/deps)")
    return True


def main():
    print("=" * 70)
    print("Building Python sidecar (infer_worker) with cx_Freeze")
    print("FULL SUPPORT: YOLO + Ultralytics + GPU (CUDA)")
    print("=" * 70)

    try:
        ensure_cxfreeze()
    except Exception as e:
        print(f"ERROR: cx_Freeze install failed: {e}")
        return False

    print("\n" + "=" * 70)
    print("Building infer_worker (YOLO + GPU)...")
    print("=" * 70)
    print("  ℹ️  Output folder: src-tauri/binaries/ (exe + deps)")
    print("  ⚠️  Pakai sys.setrecursionlimit + excludes untuk hindari RecursionError (torch/ultralytics).")
    print("  ⚠️  Jika tetap gagal: gunakan Nuitka (build:sidecar) atau PyInstaller (build:sidecar:pyinstaller).\n")

    ok = build_sidecar_cxfreeze("infer_worker.py", "infer_worker")

    if ok:
        print("\n" + "=" * 70)
        print("✓ Sidecar built with cx_Freeze!")
        print("=" * 70)
        print("\n📋 Output di src-tauri/binaries/ (folder exe + dll).")
        print("   Untuk testing: infer.rs sudah cek binaries; atau salin ke binaries/.")
        print("   Nuitka → binaries/ | PyInstaller → binaries_pyinstaller/ | cx_Freeze → binaries/")
        return True
    print("\n" + "=" * 70)
    print("✗ infer_worker cx_Freeze build failed!")
    print("=" * 70)
    print("  💡 cx_Freeze + PyTorch/Ultralytics sering RecursionError. Coba:")
    print("     npm run build:sidecar           (Nuitka)")
    print("     npm run build:sidecar:pyinstaller (PyInstaller)")
    return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
